### ISSUE TITLE
Resolve inconsistencies and errors in build image workflow

### ISSUE THREAD

**Issue by gonuke** [cnerg/learn-maintenance#15]
The `REGISTRY` and `IMAGE_NAME` are defined in the environment, but used inconsistently or not used where appropriate.  Specifically, the tag of the docker image that is build/pushed should derive from these.

Currently the push of the image fails in this merged upstream version because the image is tagged with `github.actor` instead of `github.repository` (I think).  We won't be able to test that without another merge.

**Comment by bquan0** [comment]
Something I noticed is that the steps in `testing.yml` don't use the docker image with the specified python version, which is something I added in pull request #13. I'll be adding the rest of the changes requested in this issue in that pull request.

**Comment by gonuke** [comment]
I think this was fixed in #17 ??
